name: Build Burger Stacker to GitHub pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy-pygbag:
    name: Burget Stacker Game
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            python -m pip install pygbag
            python -m pygbag --build $GITHUB_WORKSPACE/q-generated-files/main.py

    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: q-generated-files/build/web
